server:
  port: 8099

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false

  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration

  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/mail_sender_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver