CREATE TABLE IF NOT EXISTS mail
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    subject CHARACTER VARYING(255) NOT NULL,
    text TEXT NOT NULL,
    sender CHARACTER VARYING(255) NOT NULL,
    recipient CHARACTER VARYING(255) NOT NULL,
    created_date_time TIMESTAMP WITH TIME ZONE NOT NULL,
    status CHARACTER VARYING(255) NOT NULL,
    send_date_time TIMESTAMP WITH TIME ZONE,
    send_attempts SMALLINT NOT NULL DEFAULT 0,
    error_text CHARACTER VARYING(1000)
)