CREATE TABLE IF NOT EXISTS mail
(
    id BIGSERIAL NOT NULL PRIMARY KEY,
    title CHARACTER VARYING(255) NOT NULL,
    text TEXT NOT NULL,
    sender CHARACTER VARYING(255) NOT NULL,
    recipient CHARACTER VARYING(255) NOT NULL
)